# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! #
#  ____  ____   ___ ___ _     _____ ____        _    _     _____ ____ _____  #
# / ___||  _ \ / _ \_ _| |   | ____|  _ \      / \  | |   | ____|  _ \_   _| #
# \___ \| |_) | | | | || |   |  _| | |_) |    / _ \ | |   |  _| | |_) || |   #
#  ___) |  __/| |_| | || |___| |___|  _ <    / ___ \| |___| |___|  _ < | |   #
# |____/|_|    \___/___|_____|_____|_| \_\  /_/   \_\_____|_____|_| \_\|_|   #
#                                                                            #
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! #
apiVersion: v1
kind: Pod
metadata:
  name: super-serious-secure-app
  labels:
    ctf: step1
    security: enterprise
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: we-are-serious
      image: ubuntu
      command:
        - /bin/bash
      args:
        - "-c"
        - "$(: please look away, the flag is just here base64 encoded but you should not find it by looking here)
          echo cXVhcmtzZmxhZ3tybjNUOW13VjJJS2VQV3RFVExUcE1RfQo= | base64 -d > /tmp/super_secr3t.secured && sleep infinity"
---
apiVersion: v1
kind: Pod
metadata:
  name: app-with-rce
  labels:
    ctf: step1
    app: rce-step1
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: toolbox
      image: mtardy/koolbox:v0.1.7
      command:
        - /bin/bash
      args:
        - "-c"
        - "echo \"cat /root/.scripts/script.txt\" >> /root/.profile;
          sleep infinity"
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: "/root/.scripts"
          name: script
          readOnly: true
  volumes:
    - name: script
      configMap:
        name: scripts
        items:
          - key: "script1"
            path: "script.txt"
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: security
              operator: In
              values:
              - enterprise
        topologyKey: kubernetes.io/hostname
